### ISSUE TITLE
Issue running handbrake-web

### ISSUE THREAD

**Issue by tquizzle** [TheNickOfTime/handbrake-web#121]
First of all, what a brilliant concept. This is a great project.

I'm having issues running this using the example docker compose file.

I see errors in the terminal; however, the server app is launching.

```
handbrake-web-server  | > handbrake-web@0.0.0 prod
handbrake-web-server  | > tsx src/server.ts
handbrake-web-server  |
handbrake-web-server  | [server] [presets] Presets path is '/data/presets.json'
handbrake-web-server  | [server] [env] The server port is 'undefined'.
handbrake-web-server  | [server] [env] The data path is '/data'.
handbrake-web-server  | [server] [env] The video path is '/video'.
handbrake-web-server  | [server] [data] [error] Could not read data from '/data/presets.json'.
handbrake-web-server  | SyntaxError: Unexpected end of JSON input
handbrake-web-server  |     at JSON.parse (<anonymous>)
handbrake-web-server  |     at ReadDataFromFile (/handbrake-web/server/src/scripts/data.ts:20:27)
handbrake-web-server  |     at async Initialization (/handbrake-web/server/src/scripts/initialization.ts:11:18)
handbrake-web-server  | [server] [database] The database connection has been initalized!
handbrake-web-server  | [server] [queue] The queue status does not exist in the database, initializing to the state 'stopped'.
```

Is there an assumed step I am missing?

**Comment by TheNickOfTime** [comment]
Hey there! I think this error may be inconsequential. You said the server app is launching, are you seeing any issues outside of the error?

**Comment by TheNickOfTime** [comment]
This issue has been fixed in the release v0.6.1 - please run docker compose pull and restart your container :)

**Comment by tquizzle** [comment]
Actually, seeing the same issue.

```
docker compose pull
[+] Pulling 1/1
 ✔ handbrake-server Pulled

docker compose up -d
[+] Running 1/1
 ✔ Container handbrake-web-server  Started

docker compose logs
handbrake-web-server  |
handbrake-web-server  | > handbrake-web@0.0.0 prod
handbrake-web-server  | > tsx src/server.ts
handbrake-web-server  |
handbrake-web-server  | [server] [presets] Presets path is '/data/presets.json'
handbrake-web-server  | [server] [env] The server port is 'undefined'.
handbrake-web-server  | [server] [env] The data path is '/data'.
handbrake-web-server  | [server] [env] The video path is '/video'.
handbrake-web-server  | [server] [data] [error] Could not read data from '/data/presets.json'.
handbrake-web-server  | SyntaxError: Unexpected end of JSON input
handbrake-web-server  |     at JSON.parse (<anonymous>)
handbrake-web-server  |     at ReadDataFromFile (/handbrake-web/server/src/scripts/data.ts:20:27)
handbrake-web-server  |     at async Initialization (/handbrake-web/server/src/scripts/initialization.ts:13:19)
handbrake-web-server  | [server] [database] The database connection has been initalized!
handbrake-web-server  | [server] [queue] The queue status does not exist in the database, initializing to the state 'stopped'.
handbrake-web-server  | [server] Available at http://http://localhost:9999
```

The server's HTML page returns the following error as well:

```
Error
The client is unable to reach the server at http://server-ip:9999/. Please check your server status or configuration.
```

**Comment by TheNickOfTime** [comment]
Are you running the server and worker on different machines?

**Comment by tquizzle** [comment]
I have tried both as in the example as well as across two separate hosts.

Here's the output when both are ran, with a few refreshes on the page.

```
# docker compose logs -f -n 40
handbrake-worker  |
handbrake-worker  | > handbrake-web@0.0.0 prod
handbrake-worker  | > tsx src/worker.ts
handbrake-worker  |
handbrake-worker  | [worker] The worker process has started.
handbrake-worker  | [worker] [worker1] Connection to server lost, will attempt reconnection...
handbrake-worker  | [worker] [worker1] Connected to the server 'http://handbrake-server:9999/worker' with id 'fSgIBTt7WzWJMDXyAAAF'.
handbrake-server  |
handbrake-server  | > handbrake-web@0.0.0 prod
handbrake-server  | > tsx src/server.ts
handbrake-server  |
handbrake-server  | [server] [presets] Presets path is '/data/presets.json'
handbrake-server  | [server] [env] The server port is 'undefined'.
handbrake-server  | [server] [env] The data path is '/data'.
handbrake-server  | [server] [env] The video path is '/video'.
handbrake-server  | [server] [database] The database connection has been initalized!
handbrake-server  | [server] [queue] The queue status does not exist in the database, initializing to the state 'stopped'.
handbrake-server  | [server] Available at http://http://localhost:9999
handbrake-server  | [server] Client 'cOVbOAM0SS-besnyAAAC' has connected.
handbrake-server  | [server] Client 'w_vNaCwXpRtkJK5hAAAD' has connected.
handbrake-server  | [server] Worker 'worker1' has connected with ID 'fSgIBTt7WzWJMDXyAAAF'.
handbrake-server  | [server] Client 'htdZgUwqeY9wDswrAAAH' has connected.
handbrake-server  | [server] Client 'htdZgUwqeY9wDswrAAAH' has disconnected.
handbrake-server  | [server] Client 'bWH9qEju2weqv2cMAAAJ' has connected.
handbrake-server  | [server] Client 'bWH9qEju2weqv2cMAAAJ' has disconnected.
handbrake-server  | [server] Client 'vQfKWtVnLzKyCQDtAAAL' has connected.
handbrake-server  | [server] Client 'vQfKWtVnLzKyCQDtAAAL' has disconnected.
```

**Comment by TheNickOfTime** [comment]
Hmmm interesting. The worker is connecting without issues, and the server is also logging client connections as well. That means something is happening on the client side. Could you provide any logs from the browser console (press F12)? Unfortunately this is not something that I have managed to reproduce on my end.

**Comment by tquizzle** [comment]
Is the `data/config.yaml` supposed to be generated and filled? Mine is empty.
When the error for `presets.json` hits, it also does not create this file if it previously does not exist.

Could the blank config file be to blame for this behavior?

**Comment by tquizzle** [comment]
Actually - I think I've solved this.
I had removed the `user` declaration from your original yaml file.

Consider this resolved. Thank you.

**Comment by TheNickOfTime** [comment]
Oh great! Yeah I should put a note in the example compose that that value needs to be changed depending on your uuid/guid (or presumably removed if you want to run the container as root). This was likely causing permissions issues that prevented normal application operation.

**Comment by tquizzle** [comment]
Exactly. I was intentionally running as root, not expecting to see issues.

I am noticing other behavior now that I've got the stack running. 

When on the Queue page and creating a new job, the container is hardcoded to `/video/input`, whereas the example compose file mounts `/video` in the container. This was causing me issues as the `input` folder did not exist as a subfolder to `video`.

I'm also having issues encoding. All errors are `Encode failed error 3`.
I have tried a couple of different source files and Handbrake presets.

```
handbrake-worker  | [worker] [error]  udfread ERROR: ECMA 167 Volume Recognition failed
handbrake-worker  |
handbrake-worker  | [worker] [error]  disc.c:333: failed opening UDF image /video/input/VIDEOFILE.mkv
handbrake-worker  | disc.c:437: error opening file BDMV/index.bdmv
handbrake-worker  | disc.c:437: error opening file BDMV/BACKUP/index.bdmv
handbrake-worker  | [22:52:29] bd: not a bd - trying as a stream/file instead
handbrake-worker  |
handbrake-worker  | [worker] [error]  libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
handbrake-worker  | libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
handbrake-worker  | [worker] [error]
handbrake-worker  | [22:52:29] dvd: not a dvd - trying as a stream/file instead
handbrake-worker  |
handbrake-worker  | [worker] [error]  Input #0, matroska,webm, from '/video/input/VIDEOFILE.mkv':
handbrake-worker  |   Metadata:
handbrake-worker  |     ENCODER         : Lavf59.16.100
handbrake-worker  |   Duration: 02:03:02.40, start: 0.000000, bitrate: 5434 kb/s
```

After this
That might be a normal process, however...after interrogating the file, I started to see the issues:

```
handbrake-worker  | [worker] [transcode] [version] {
handbrake-worker  |   Arch: 'x86_64',
handbrake-worker  |   Name: 'HandBrake',
handbrake-worker  |   Official: true,
handbrake-worker  |   RepoDate: '2023-01-22 16:36:49',
handbrake-worker  |   RepoHash: '04413a27e6d616cddd98c2c6468aca2bf91b87b5',
handbrake-worker  |   System: 'Linux',
handbrake-worker  |   Type: 'release',
handbrake-worker  |   Version: { Major: 1, Minor: 6, Point: 1 },
handbrake-worker  |   VersionString: '1.6.1'
handbrake-worker  | }
handbrake-worker  | [worker] [transcode] [scanning] 60.00 %
handbrake-worker  | [worker] [transcode] [processing] 7.96 %
handbrake-worker  | [worker] [transcode] [processing] 16.31 %
handbrake-worker  | [worker] [transcode] [processing] 24.67 %
handbrake-worker  | [worker] [transcode] [processing] 33.51 %
handbrake-worker  | [worker] [transcode] [processing] 42.02 %
handbrake-worker  | [worker] [transcode] [processing] 50.60 %
handbrake-worker  | [worker] [transcode] [processing] 59.34 %
handbrake-worker  | [worker] [transcode] [processing] 67.79 %
handbrake-worker  | [worker] [error]  [22:52:33] reader: done. 1 scr changes
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] work: average encoding speed for job is 0.000000 fps
handbrake-worker  | [22:52:33] comb detect: heavy 0 | light 0 | uncombed 0 | total 0
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] vfr: 0 frames output, 0 dropped and 0 duped for CFR/PFR
handbrake-worker  | [22:52:33] vfr: lost time: 0 (0 frames)
handbrake-worker  | [22:52:33] vfr: gained time: 0 (0 frames) (0 not accounted for)
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] hevc-decoder done: 0 frames, 0 decoder errors
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] sync: got 0 frames, 177000 expected
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] Subtitle track 0 (id 0x3) 'English [PGS]': 1393 hits (0 forced)
handbrake-worker  | [22:52:33] Subtitle track 4 (id 0x7) 'English [PGS]': 1957 hits (0 forced)
handbrake-worker  | [22:52:33] No candidate detected during subtitle scan
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] Starting Task: Encoding Pass
handbrake-worker  | [22:52:33] Skipping crop/scale filter
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] job configuration:
handbrake-worker  | [22:52:33]  * source
handbrake-worker  | [22:52:33]    + /video/input/VIDEOFILE.mkv
handbrake-worker  | [22:52:33]    + title 1, chapter(s) 1 to 24
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33]    + container: matroska,webm
handbrake-worker  | [22:52:33]    + data rate: 5434 kbps
handbrake-worker  | [22:52:33]  * destination
handbrake-worker  | [22:52:33]    + /video/input/VIDEOFILE.transcoding.mkv
handbrake-worker  | [22:52:33]    + container: Matroska (libavformat)
handbrake-worker  | [22:52:33]      + align initial A/V stream timestamps
handbrake-worker  | [22:52:33]      + chapter markers
handbrake-worker  | [22:52:33]  * video track
handbrake-worker  | [22:52:33]    + decoder: hevc 8-bit (yuv420p)
handbrake-worker  | [22:52:33]    + filters
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33]      + Comb Detect (mode=0:spatial-metric=2:motion-thresh=2:spatial-thresh=3:filter-mode=1:block-thresh=80:block-width=16:block-height=16)
handbrake-worker  | [22:52:33]      + Decomb (mode=39)
handbrake-worker  | [22:52:33]      + Framerate Shaper (mode=2:rate=27000000/900000)
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33]        + frame rate: 23.976 fps -> peak rate limited to 30.000 fps
handbrake-worker  | [22:52:33]    + Output geometry
handbrake-worker  | [22:52:33]      + storage dimensions: 1280 x 536
handbrake-worker  | [22:52:33]      + pixel aspect ratio: 1 : 1
handbrake-worker  | [22:52:33]      + display dimensions: 1280 x 536
handbrake-worker  | [22:52:33]    + encoder: H.264 (libx264)
handbrake-worker  | [22:52:33]      + preset:  veryfast
handbrake-worker  | [22:52:33]      + profile: main
handbrake-worker  | [22:52:33]      + level:   3.1
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33]      + quality: 23.00 (RF)
handbrake-worker  | [22:52:33]      + color profile: 1-1-1
handbrake-worker  | [22:52:33]      + chroma location: left
handbrake-worker  | [22:52:33]  * audio track 1
handbrake-worker  | [22:52:33]    + name: AC3 5.1
handbrake-worker  | [22:52:33]    + decoder: English (AC3) (5.1 ch) (640 kbps) (track 1, id 0x1)
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33]      + bitrate: 640 kbps, samplerate: 48000 Hz
handbrake-worker  | [22:52:33]    + mixdown: Stereo
handbrake-worker  | [22:52:33]    + encoder: AAC (libavcodec)
handbrake-worker  | [22:52:33]      + bitrate: 160 kbps, samplerate: 48000 Hz
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] sync: expecting 177000 video frames
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] encx264: min-keyint: 24, keyint: 240
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] encx264: encoding at constant RF 23.000000
handbrake-worker  | [22:52:33] encx264: unparsed options: level=3.1:ref=1:8x8dct=0:weightp=1:subme=2:mixed-refs=0:trellis=0:vbv-bufsize=14000:vbv-maxrate=14000:rc-lookahead=10
handbrake-worker  |
handbrake-worker  | [worker] [error]  x264 [info]: using SAR=1/1
handbrake-worker  |
handbrake-worker  | [worker] [error]  x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
handbrake-worker  |
handbrake-worker  | [worker] [error]  x264 [info]: profile Main, level 3.1, 4:2:0, 8-bit
handbrake-worker  |
handbrake-worker  | [worker] [error]  ERROR: avio_open2 failed, errno -13
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] work: average encoding speed for job is 0.000000 fps
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] comb detect: heavy 0 | light 0 | uncombed 0 | total 0
handbrake-worker  | [22:52:33] vfr: 0 frames output, 0 dropped and 0 duped for CFR/PFR
handbrake-worker  | [22:52:33] vfr: lost time: 0 (0 frames)
handbrake-worker  | [22:52:33] vfr: gained time: 0 (0 frames) (0 not accounted for)
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] ac3-decoder done: 0 frames, 0 decoder errors
handbrake-worker  | [22:52:33] hevc-decoder done: 0 frames, 0 decoder errors
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] sync: got 0 frames, 177000 expected
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] Finished work at: Wed Aug 14 22:52:33 2024
handbrake-worker  |
handbrake-worker  |
handbrake-worker  | [worker] [error]  [22:52:33] libhb: work result = 3
handbrake-worker  |
handbrake-worker  | [worker] [error]
handbrake-worker  | Encode failed (error 3).
handbrake-worker  |
handbrake-worker  | [worker] [error]  HandBrake has exited.
handbrake-worker  |
handbrake-worker  | [worker] [transcode] [processing] 84.25 %
handbrake-worker  | [worker] [transcode] [processing] 92.51 %
handbrake-worker  | [worker] [transcode] [processing] 100.00 %
handbrake-worker  | [worker] [transcode] [processing] 0.00 %
handbrake-worker  | [worker] [transcode] [error] Finished with error 3
```

**Comment by TheNickOfTime** [comment]
In regards to the path stuff, this can be controlled via a config file that would be in your mapped data directory. Unfortunately there isn't documentation about this at the moment (something I need to work on). But the good news is that there will be a settings page in the next release to more easily control some of these factors.

In regards to the error, I'll have to look into this as I have not experienced it on my end. My hunch says it may be permissions related - for example if the directory you have mapped to /video has different permissions than the user you are running the container as. That said it seems like you are running the container as root so permissions shouldn't be an issue?
